spring:
  # 制定session数据库
  session:
    store-type: redis

  # REDIS (RedisProperties)
  # 其中spring.redis.database的配置通常使用0即可，
  # Redis在配置的时候可以设置数据库数量，默认为16，可以理解为数据库的schema
  redis:
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器地址
    host: localhost
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    # password:
    # 连接超时时间（毫秒）
    timeout: 0
    pool:
      # 连接池最大连接数（使用负值表示没有限制）
      max-active: 20
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1
      # 连接池中的最大空闲连接
      max-idle: 10
      # 连接池中的最小空闲连接
      min-idle: 0
